"""
ClauseGuard AI - Executive Audit Report Generator
Outputs:
1. GitHub-Flavored Markdown (.md)
2. Standalone Executive Print/PDF HTML Document with Print Stylesheets
3. Compact Executive Summary for Clipboard / Email
"""

import datetime
from typing import Dict, Any, List


def generate_markdown_report(analysis: Dict[str, Any]) -> str:
    """Generate a clean, professional GitHub-Flavored Markdown audit report."""
    filename = analysis.get("filename", "agreement.txt")
    metadata = analysis.get("metadata", {})
    summary = analysis.get("risk_summary", {})
    metrics = summary.get("metrics", {})
    findings = analysis.get("findings", [])
    doc_meta = analysis.get("document_meta", {})
    now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    score = summary.get("score", 0)
    grade = summary.get("grade", "Unknown")
    recommendation = summary.get("recommendation", "")

    # Score Emoji
    if score >= 75:
        score_badge = f"🟢 **{score}/100 - LOW RISK**"
    elif score >= 45:
        score_badge = f"🟡 **{score}/100 - MODERATE / HIGH RISK**"
    else:
        score_badge = f"🔴 **{score}/100 - CRITICAL RISK**"

    lines = [
        f"# 🛡️ ClauseGuard AI — Executive Contract Risk Audit Report",
        f"",
        f"**Audit Generated**: {now_str}  ",
        f"**Document Filename**: `{filename}`  ",
        f"**Contract Classification**: {metadata.get('contract_type', 'Commercial Agreement')}  ",
        f"",
        f"---",
        f"",
        f"## 1. Executive Summary & Risk Score",
        f"",
        f"| Metric | Audit Result |",
        f"| :--- | :--- |",
        f"| **Overall Risk Score** | {score_badge} |",
        f"| **Risk Classification** | **{grade}** |",
        f"| **Critical Red Flags** | `{metrics.get('critical_flags', 0)}` |",
        f"| **High-Risk Items** | `{metrics.get('high_flags', 0)}` |",
        f"| **Cautionary Warnings** | `{metrics.get('warnings', 0)}` |",
        f"| **Favorable Protections** | `{metrics.get('favorable_clauses', 0)}` |",
        f"| **Total Clauses Audited** | `{metrics.get('total_audited', len(findings))}` |",
        f"",
        f"> **Executive Recommendation**  ",
        f"> {recommendation}",
        f"",
        f"---",
        f"",
        f"## 2. Agreement Metadata",
        f"",
        f"| Parameter | Identified Value |",
        f"| :--- | :--- |",
        f"| **Governing Law / Jurisdiction** | {metadata.get('governing_law', 'Not specified')} |",
        f"| **Identified Parties** | {', '.join(metadata.get('parties', ['Unspecified'])) if metadata.get('parties') else 'Unspecified'} |",
        f"| **Agreement Term** | {metadata.get('term', 'Not specified')} |",
        f"| **Liability Cap Status** | {metadata.get('liability_cap_status', 'Unknown')} |",
        f"| **Estimated Pages** | {doc_meta.get('total_pages', 1)} |",
        f"| **Character Count** | {doc_meta.get('char_count', 'N/A'):,} characters |" if isinstance(doc_meta.get('char_count'), (int, float)) else f"| **Character Count** | {doc_meta.get('char_count', 'N/A')} |",
        f"",
        f"---",
        f"",
        f"## 3. Detailed Audit Findings & Counter-Proposals",
        f""
    ]

    if not findings:
        lines.append("✅ **No critical red flags or severe contractual risks detected.** The agreement adheres to standard commercial protections.")
    else:
        for idx, item in enumerate(findings, start=1):
            severity = item.get("severity", "warning").lower()
            if severity == "critical":
                badge = "🔴 **CRITICAL RISK**"
            elif severity == "high":
                badge = "🟠 **HIGH RISK**"
            elif severity == "favorable":
                badge = "🟢 **FAVORABLE PROTECTION**"
            else:
                badge = "🟡 **CAUTION / WARNING**"

            lines.extend([
                f"### Finding #{idx}: {item.get('title', 'Contractual Term')} ({badge})",
                f"",
                f"- **Category**: {item.get('category', 'General')}",
                f"- **Relevant Section**: {item.get('section', 'General Provisions')}",
                f"",
                f"#### Original Flagged Language:",
                f"```text",
                f"{item.get('clause_excerpt', '').strip()}",
                f"```",
                f"",
                f"#### Risk Analysis & Exposure:",
                f"{item.get('explanation', '')}",
                f"",
                f"#### Recommended Counter-Proposal (Redline Language):",
                f"> 💡 **Suggested Amendment:**  ",
                f"> {item.get('counter_proposal', '')}",
                f"",
                f"---",
                f""
            ])

    lines.extend([
        f"## 4. Legal Disclaimer",
        f"",
        f"*This report was autonomously generated by ClauseGuard AI using heuristic and machine-learning risk intelligence engines. It provides automated risk assessment and drafting recommendations for negotiation assistance only, and does not constitute formal legal counsel. Prior to executing binding legal instruments, review with qualified legal counsel in your governing jurisdiction.*",
        f"",
        f"---",
        f"*ClauseGuard AI — Enterprise Contract Intelligence • https://clauseguard.alpfrtech.com*"
    ])

    return "\n".join(lines)


def generate_summary_text(analysis: Dict[str, Any]) -> str:
    """Generate a compact summary text string ideal for clipboard copying or email briefing."""
    filename = analysis.get("filename", "agreement.txt")
    summary = analysis.get("risk_summary", {})
    metrics = summary.get("metrics", {})
    findings = analysis.get("findings", [])
    
    score = summary.get("score", 0)
    grade = summary.get("grade", "Unknown")
    
    top_findings = [f"- [{f.get('severity', '').upper()}] {f.get('title', '')}" for f in findings[:4]]
    findings_str = "\n".join(top_findings) if top_findings else "- No severe flags detected"

    return f"""🛡️ ClauseGuard AI Audit Summary: {filename}
Risk Score: {score}/100 ({grade})
Critical Flags: {metrics.get('critical_flags', 0)} | High Flags: {metrics.get('high_flags', 0)} | Warnings: {metrics.get('warnings', 0)}

Key Areas of Concern:
{findings_str}

Recommendation:
{summary.get('recommendation', 'Review clauses before execution.')}

Audited at: https://clauseguard.alpfrtech.com"""


def generate_html_report(analysis: Dict[str, Any]) -> str:
    """Generate a self-contained, executive-grade printable HTML report with print stylesheets."""
    filename = analysis.get("filename", "agreement.txt")
    metadata = analysis.get("metadata", {})
    summary = analysis.get("risk_summary", {})
    metrics = summary.get("metrics", {})
    findings = analysis.get("findings", [])
    doc_meta = analysis.get("document_meta", {})
    now_str = datetime.datetime.now(datetime.timezone.utc).strftime("%B %d, %Y - %H:%M UTC")

    score = summary.get("score", 0)
    grade = summary.get("grade", "Unknown")
    recommendation = summary.get("recommendation", "")

    # Score Color Theme
    if score >= 75:
        score_color = "#10b981"
        badge_class = "score-low"
    elif score >= 45:
        score_color = "#f59e0b"
        badge_class = "score-med"
    else:
        score_color = "#ef4444"
        badge_class = "score-high"

    findings_html_list = []
    for idx, f in enumerate(findings, start=1):
        sev = f.get("severity", "warning").lower()
        if sev == "critical":
            sev_class = "badge-critical"
            sev_label = "CRITICAL"
        elif sev == "high":
            sev_class = "badge-high"
            sev_label = "HIGH"
        elif sev == "favorable":
            sev_class = "badge-favorable"
            sev_label = "FAVORABLE"
        else:
            sev_class = "badge-warning"
            sev_label = "WARNING"

        findings_html_list.append(f"""
        <div class="finding-card">
          <div class="finding-header">
            <span class="finding-index">Finding #{idx}</span>
            <span class="badge {sev_class}">{sev_label}</span>
            <h3 class="finding-title">{f.get('title', 'Term')}</h3>
            <span class="finding-meta">{f.get('category', 'General')} • {f.get('section', 'General Provisions')}</span>
          </div>

          <div class="finding-body">
            <div class="clause-box">
              <div class="box-label">Original Flagged Language</div>
              <p class="clause-text">"{f.get('clause_excerpt', '').strip()}"</p>
            </div>

            <div class="explanation-box">
              <div class="box-label">Risk Analysis & Exposure</div>
              <p>{f.get('explanation', '')}</p>
            </div>

            <div class="proposal-box">
              <div class="box-label">Recommended Counter-Proposal (Redline Language)</div>
              <p class="proposal-text">{f.get('counter_proposal', '')}</p>
            </div>
          </div>
        </div>
        """)

    findings_content = "".join(findings_html_list) if findings_html_list else "<p class='no-findings'>No critical risks detected. Standard commercial terms apply.</p>"

    parties_str = ", ".join(metadata.get('parties', [])) if metadata.get('parties') else "Unspecified"
    char_count = doc_meta.get('char_count', 'N/A')
    char_count_fmt = f"{char_count:,}" if isinstance(char_count, (int, float)) else str(char_count)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ClauseGuard AI - Executive Audit Report: {filename}</title>
  <style>
    :root {{
      --primary: #0284c7;
      --text: #0f172a;
      --text-muted: #64748b;
      --bg: #ffffff;
      --card-bg: #f8fafc;
      --border: #e2e8f0;
      --critical: #ef4444;
      --high: #f97316;
      --warning: #f59e0b;
      --favorable: #10b981;
    }}

    * {{
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }}

    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: var(--text);
      background: #f1f5f9;
      line-height: 1.5;
      padding: 24px;
    }}

    .report-container {{
      max-width: 900px;
      margin: 0 auto;
      background: var(--bg);
      border-radius: 12px;
      box-shadow: 0 4px 20px rgba(0,0,0,0.08);
      padding: 40px;
    }}

    /* Print / Action Header */
    .action-bar {{
      display: flex;
      justify-content: flex-end;
      gap: 12px;
      margin-bottom: 24px;
    }}

    .btn {{
      padding: 8px 16px;
      font-size: 14px;
      font-weight: 600;
      border-radius: 6px;
      cursor: pointer;
      border: 1px solid var(--border);
      background: #ffffff;
      color: var(--text);
      transition: all 0.2s;
    }}

    .btn-primary {{
      background: var(--primary);
      color: #ffffff;
      border-color: var(--primary);
    }}

    .btn:hover {{
      opacity: 0.9;
    }}

    /* Header */
    .header {{
      border-bottom: 2px solid var(--border);
      padding-bottom: 24px;
      margin-bottom: 28px;
    }}

    .brand {{
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 8px;
    }}

    .brand-icon {{
      font-size: 28px;
    }}

    .brand-title {{
      font-size: 24px;
      font-weight: 800;
      letter-spacing: -0.5px;
      color: #0284c7;
    }}

    .report-subtitle {{
      font-size: 14px;
      color: var(--text-muted);
      margin-top: 4px;
    }}

    /* Executive Score Card */
    .score-card {{
      display: grid;
      grid-template-columns: 160px 1fr;
      gap: 24px;
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 24px;
      margin-bottom: 28px;
      align-items: center;
    }}

    .score-circle {{
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 140px;
      height: 140px;
      border-radius: 50%;
      border: 8px solid {score_color};
      background: #ffffff;
      margin: 0 auto;
    }}

    .score-num {{
      font-size: 38px;
      font-weight: 900;
      color: {score_color};
      line-height: 1;
    }}

    .score-label {{
      font-size: 11px;
      font-weight: 700;
      color: var(--text-muted);
      text-transform: uppercase;
      margin-top: 4px;
    }}

    .score-details h2 {{
      font-size: 20px;
      font-weight: 750;
      color: var(--text);
      margin-bottom: 6px;
    }}

    .recommendation-text {{
      font-size: 14px;
      color: var(--text);
      line-height: 1.5;
      margin-bottom: 16px;
    }}

    .metrics-row {{
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
    }}

    .metric-pill {{
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: #ffffff;
      border: 1px solid var(--border);
      padding: 4px 10px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 600;
    }}

    /* Metadata Table */
    .section-title {{
      font-size: 18px;
      font-weight: 750;
      color: var(--text);
      margin-bottom: 14px;
      display: flex;
      align-items: center;
      gap: 8px;
    }}

    .metadata-grid {{
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 12px;
      margin-bottom: 32px;
    }}

    .meta-item {{
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 6px;
      padding: 10px 14px;
    }}

    .meta-label {{
      font-size: 11px;
      text-transform: uppercase;
      color: var(--text-muted);
      font-weight: 700;
    }}

    .meta-val {{
      font-size: 14px;
      font-weight: 600;
      color: var(--text);
      margin-top: 2px;
    }}

    /* Findings Cards */
    .finding-card {{
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
      page-break-inside: avoid;
    }}

    .finding-header {{
      display: flex;
      align-items: center;
      gap: 10px;
      flex-wrap: wrap;
      margin-bottom: 14px;
      border-bottom: 1px solid var(--border);
      padding-bottom: 10px;
    }}

    .finding-index {{
      font-size: 12px;
      font-weight: 700;
      color: var(--text-muted);
    }}

    .badge {{
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 750;
      letter-spacing: 0.5px;
      text-transform: uppercase;
    }}

    .badge-critical {{ background: #fee2e2; color: #b91c1c; border: 1px solid #fca5a5; }}
    .badge-high {{ background: #ffedd5; color: #c2410c; border: 1px solid #fdba74; }}
    .badge-warning {{ background: #fef3c7; color: #b45309; border: 1px solid #fde68a; }}
    .badge-favorable {{ background: #d1fae5; color: #047857; border: 1px solid #a7f3d0; }}

    .finding-title {{
      font-size: 16px;
      font-weight: 700;
      color: var(--text);
      flex: 1;
    }}

    .finding-meta {{
      font-size: 12px;
      color: var(--text-muted);
    }}

    .finding-body {{
      display: flex;
      flex-direction: column;
      gap: 12px;
    }}

    .box-label {{
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: var(--text-muted);
      margin-bottom: 4px;
    }}

    .clause-box {{
      background: #f1f5f9;
      border-left: 4px solid #64748b;
      padding: 10px 14px;
      border-radius: 0 6px 6px 0;
    }}

    .clause-text {{
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 13px;
      color: #334155;
      font-style: italic;
    }}

    .explanation-box p {{
      font-size: 13.5px;
      color: var(--text);
    }}

    .proposal-box {{
      background: #ecfdf5;
      border-left: 4px solid var(--favorable);
      padding: 10px 14px;
      border-radius: 0 6px 6px 0;
    }}

    .proposal-text {{
      font-size: 13.5px;
      color: #065f46;
      font-weight: 500;
    }}

    /* Footer / Disclaimer */
    .disclaimer {{
      border-top: 1px solid var(--border);
      padding-top: 20px;
      margin-top: 36px;
      font-size: 11.5px;
      color: var(--text-muted);
      line-height: 1.6;
    }}

    /* Print Stylesheet */
    @media print {{
      body {{
        background: #ffffff;
        padding: 0;
      }}
      .report-container {{
        box-shadow: none;
        padding: 0;
        max-width: 100%;
      }}
      .action-bar {{
        display: none !important;
      }}
      .finding-card {{
        page-break-inside: avoid;
      }}
    }}
  </style>
</head>
<body>

  <div class="report-container">

    <!-- Action Bar for Screen View -->
    <div class="action-bar">
      <button class="btn" onclick="window.close()">Close</button>
      <button class="btn btn-primary" onclick="window.print()">🖨️ Print / Save as PDF</button>
    </div>

    <!-- Header -->
    <div class="header">
      <div class="brand">
        <span class="brand-icon">🛡️</span>
        <span class="brand-title">ClauseGuard AI</span>
      </div>
      <h1 style="font-size: 22px; font-weight: 800; margin-top: 4px;">Executive Contract Risk Audit</h1>
      <div class="report-subtitle">
        Document: <strong>{filename}</strong> • Generated: {now_str}
      </div>
    </div>

    <!-- Executive Score Card -->
    <div class="score-card">
      <div class="score-circle">
        <span class="score-num">{score}</span>
        <span class="score-label">{grade}</span>
      </div>
      <div class="score-details">
        <h2>Risk Assessment: {grade}</h2>
        <p class="recommendation-text">{recommendation}</p>
        <div class="metrics-row">
          <span class="metric-pill" style="color: #b91c1c;">🔴 {metrics.get('critical_flags', 0)} Critical</span>
          <span class="metric-pill" style="color: #c2410c;">🟠 {metrics.get('high_flags', 0)} High Risk</span>
          <span class="metric-pill" style="color: #b45309;">🟡 {metrics.get('warnings', 0)} Warnings</span>
          <span class="metric-pill" style="color: #047857;">🟢 {metrics.get('favorable_clauses', 0)} Favorable</span>
        </div>
      </div>
    </div>

    <!-- Agreement Metadata -->
    <h2 class="section-title">📄 Agreement Parameters</h2>
    <div class="metadata-grid">
      <div class="meta-item">
        <div class="meta-label">Contract Classification</div>
        <div class="meta-val">{metadata.get('contract_type', 'Commercial Agreement')}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Governing Law / Jurisdiction</div>
        <div class="meta-val">{metadata.get('governing_law', 'Not specified')}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Identified Parties</div>
        <div class="meta-val">{parties_str}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Liability Cap Status</div>
        <div class="meta-val">{metadata.get('liability_cap_status', 'Unknown')}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Agreement Term</div>
        <div class="meta-val">{metadata.get('term', 'Not specified')}</div>
      </div>
      <div class="meta-item">
        <div class="meta-label">Document Size</div>
        <div class="meta-val">{char_count_fmt} characters ({doc_meta.get('total_pages', 1)} pages)</div>
      </div>
    </div>

    <!-- Audit Findings -->
    <h2 class="section-title">🔍 Identified Red Flags & Redline Recommendations ({len(findings)})</h2>
    {findings_content}

    <!-- Disclaimer -->
    <div class="disclaimer">
      <strong>Legal Disclaimer:</strong> This document was prepared autonomously by ClauseGuard AI. The scores, categorized risk assessments, and counter-proposal redlines are provided for informational and negotiation support purposes only, and do not constitute formal legal advice. Please consult with qualified legal counsel before signing binding legal commitments.
      <br><br>
      <em>ClauseGuard AI • https://clauseguard.alpfrtech.com</em>
    </div>

  </div>

</body>
</html>
"""
    return html
